const avro = require("avsc");
const type = avro.Type.forSchema({
  type: "record",
  name: "redbook_hccorevehicle",
  namespace: "com.pickles.redbookdata",
  fields: [
    { name: "dateTimeOccurred", type: ["null", "string"], default: null },
    { name: "eventSource", type: ["null", "string"], default: null },
    { name: "eventType", type: ["null", "string"], default: null },
    { name: "eventId", type: ["null", "string"], default: null },
    { name: "domainCorrelationId", type: ["null", "string"], default: null },
    { name: "schema", type: ["null", "string"], default: null },
    { name: "topic", type: ["null", "string"], default: null },
    {
      name: "data",
      type: [
        "null",
        {
          type: "record",
          name: "data",
          fields: [
            { name: "Sourcetable", type: ["null", "string"], default: null },
            { name: "Hccorevehicleid", type: ["null", "float"], default: null },
            { name: "Vehiclekeylegacy", type: ["null", "string"], default: null },
            { name: "Vehiclekey", type: ["null", "string"], default: null },
            { name: "Make", type: ["null", "string"], default: null },
            { name: "Family", type: ["null", "string"], default: null },
            { name: "Vehicletypecode", type: ["null", "string"], default: null },
            { name: "Yeargroup", type: ["null", "float"], default: null },
            { name: "Monthgroup", type: ["null", "string"], default: null },
            { name: "Sequencenum", type: ["null", "float"], default: null },
            { name: "Description", type: ["null", "string"], default: null },
            { name: "Currentrelease", type: ["null", "string"], default: null },
            { name: "Importflag", type: ["null", "string"], default: null },
            { name: "Limitededition", type: ["null", "string"], default: null },
            { name: "Seriespublic", type: ["null", "string"], default: null },
            { name: "Seriesmodelyear", type: ["null", "float"], default: null },
            { name: "Badgedescription", type: ["null", "string"], default: null },
            { name: "Badgesecondarydescription", type: ["null", "string"], default: null },
            { name: "Bodystyledescription", type: ["null", "string"], default: null },
            { name: "Bodyconfigdescription", type: ["null", "string"], default: null },
            { name: "Wheelbaseconfig", type: ["null", "string"], default: null },
            { name: "Roofline", type: ["null", "string"], default: null },
            { name: "Extraidentification", type: ["null", "string"], default: null },
            { name: "Drivedescription", type: ["null", "string"], default: null },
            { name: "Geartypedescription", type: ["null", "string"], default: null },
            { name: "Gearlocationdescription", type: ["null", "string"], default: null },
            { name: "Gearnum", type: ["null", "float"], default: null },
            { name: "Manufacturergeartype", type: ["null", "string"], default: null },
            { name: "Remarks", type: ["null", "string"], default: null },
            { name: "Doornum", type: ["null", "float"], default: null },
            { name: "Enginesize", type: ["null", "float"], default: null },
            { name: "Enginedescription", type: ["null", "string"], default: null },
            { name: "Cylinders", type: ["null", "float"], default: null },
            { name: "Fueltypedescription", type: ["null", "string"], default: null },
            { name: "Inductiondescription", type: ["null", "string"], default: null },
            { name: "Optioncategory", type: ["null", "string"], default: null },
            { name: "Grossvehiclemass", type: ["null", "float"], default: null },
            { name: "Payload", type: ["null", "string"], default: null },
            { name: "Grosscombinationmass", type: ["null", "float"], default: null },
            { name: "Vin", type: ["null", "string"], default: null },
            { name: "Enginenum", type: ["null", "string"], default: null },
            { name: "Vehicletypedescription", type: ["null", "string"], default: null },
            { name: "Avgwholesale", type: ["null", "float"], default: null },
            { name: "Newprice", type: ["null", "float"], default: null },
          ],
        },
      ],
      default: null,
    },
  ],
});
let data = 'AjQyMDIwLTExLTI0IDA1OjE1OjI1LjcxODAwMAIOUkVEQk9PSwIcUmVjb3JkSW5zZXJ0ZWQCSDljMDk2ZjAyLTI1YjAtNGI1Zi1iZTA1LWM3ZDJhY2RkZThkZgJIZjMwNzQwZTItYTMzYi00YmQzLWJmMjEtZTg5NmVhN2RjNTAyAghOb25lAmp0ZXN0LnBpY2tsZXMucGlja2xlc2F1Y3Rpb25zLmRhdGF3YXJlaG91c2UuZHcucmVkYm9vawICKnJlZGJvb2tfaGNjb3JldmVoaWNsZQIAAFBDAhBCQ0kgMTZCSAIeQVVWQkNJXzIwMTZBRUJIAgZCQ0kCEEV4cGxvcmVyAgRIQwIAAPxEAgIwAgAAAAACTDY1c3QgQnVzIDZ4MiAxMC44RFQsIEdWTToyNDUwMGtnIChBL1MpAgJGAgJMAgJGAAAAAAIGQnVzAAAAAgZBL1MCBjZ4MgISQXV0b21hdGljAghEYXNoAgAAwEACDkFsbGlzb24CrAJBbGxpc29uIFQ0NTBSIDYgc3BlZWQgYXV0b21hdGljIHRyYW5zbWlzc2lvbi5Db2FjaCBib2R5ICA0NSAtIDY1IHBhc3NlbmdlciBzZWF0cy5EaW1lbnNpb25zOjEyNTAwLzEzNzAwLzE0NTAwIG92ZXJhbGwgbGVuZ3RoLTM4MjAvMzk3MCAoSGkgRGVjaykgaGlnaC4CAACAPwIAwChGAggxMC44AgAAwEACDERpZXNlbAIiVHVyYm8gSW50ZXJjb29sZWQCBEhDAgBov0YAAAACEDcxMDA1NjUxAiBIZWF2eSBDb21tZXJjaWFsAAA=';
let buff = new Buffer(data, 'base64');

console.log(type.fromBuffer(buff));
